[git_status]
conflicted = 'ğŸ³${count} '
ahead = 'ğŸâ‡¡${count} '
behind = 'ğŸ˜°â‡£${count} '
diverged = 'ğŸ˜µâ‡•â‡¡${ahead_count}â‡£${behind_count} '
up_to_date = 'âœ“'
untracked = 'ğŸ¤·${count} '
stashed = 'ğŸ“¦${count} '
modified = 'ğŸ“${count} '
staged = '[++\($count\)](green) '
renamed = 'ğŸ‘…${count} '
deleted = 'ğŸ—‘${count} '
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
