[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[git_status]
conflicted = 'ğŸ³ ${count} '
ahead = 'ğŸ â‡¡${count} '
behind = 'ğŸ˜° â‡£${count} '
diverged = 'ğŸ˜µ â‡•â‡¡${ahead_count}â‡£${behind_count} '
up_to_date = 'âœ“'
untracked = 'ğŸ¤· ${count} '
stashed = 'ğŸ“¦ ${count} '
modified = 'ğŸ“ ${count} '
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘… ${count} '
deleted = 'ğŸ—‘ ${count} '

